"""empty message

Revision ID: 487769f4f356
Revises: 8caaef225994
Create Date: 2019-09-14 19:51:05.087945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487769f4f356'
down_revision = '8caaef225994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'datetimeend',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'datetimeend',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
