"""empty message

Revision ID: 7fec3b959750
Revises: b08be2aa27b2
Create Date: 2019-09-12 22:32:17.626265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fec3b959750'
down_revision = 'b08be2aa27b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('body', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('title', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'views')
    op.drop_column('posts', 'updated')
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'created')
    op.drop_column('posts', 'body')
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
