"""empty message

Revision ID: 8caaef225994
Revises: f2f5a3114e21
Create Date: 2019-09-14 19:44:11.495999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8caaef225994'
down_revision = 'f2f5a3114e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'datetimeend',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'datetimeend',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
