"""empty message

Revision ID: b08be2aa27b2
Revises: e0ab337d722a
Create Date: 2019-09-12 22:31:57.465918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b08be2aa27b2'
down_revision = 'e0ab337d722a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_author_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'body')
    op.drop_column('posts', 'author')
    op.drop_column('posts', 'updated')
    op.drop_column('posts', 'views')
    op.drop_column('posts', 'created')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_author_fkey', 'posts', 'users', ['author'], ['id'])
    # ### end Alembic commands ###
