"""empty message

Revision ID: f7ad24434c28
Revises: 7fec3b959750
Create Date: 2019-09-12 22:43:19.010892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ad24434c28'
down_revision = '7fec3b959750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('image_url', sa.String(length=200), nullable=False))
    op.add_column('events', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('time', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=13), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'address')
    op.drop_column('events', 'time')
    op.drop_column('events', 'price')
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'address')
    # ### end Alembic commands ###
